### PR TITLE
Feature/sieve filters

### PR DESCRIPTION
**Pull request by mmittelb**
I merged the view and tried to use the api to get scripts. But I only get internal server errors. The message in the log file: 
"Exception":"Horde\\ManageSieve\\Exception\\NotAuthenticated","Message":"Not currently in AUTHENTICATED state"
In my mailserver log I cannot find any attempt to authenticate to the managesieve server.
Any idea what's happening?

### CODE REVIEW

**Comment by pierlon** [comment]
Hey @mmittelb sorry for getting back to you so late. Did you configure a Sieve account in the settings?

Will look at your progress so far and get it merged.

**Comment by pierlon** [comment]
Took a look at your changes. It looks like you're mistaken the account settings for the global mail settings. I've already added a "Filters" section and Sieve account settings to accounts for them to be configured. Check the example below to find the account settings:

Sieve account settings

I see you've started making the UI to customize filters, which is great! To summarize my to-do list, all that's needed now is:

- a UI to add and customize filters
- generate a Sieve script from editable filters
- convert saved Sieve script back to editable filters

**Comment by mmittelb** [comment]
Hey good to hear from you.

> Took a look at your changes. It looks like you're mistaken the account settings for the global mail settings. I've already added a "Filters" section and Sieve account settings to accounts for them to be configured. Check the example below to find the account settings:

I saw that section and configured the sieve parameters. But when I tried to load scripts with your getScripts function in 'src/service/FiltersService.js' I ran into that error. If you want to reproduce you can change the const scripts variable in the fetchSieveScripts action (src/store/actions.js) and uncomment the created() part in 'src/components/SieveFilterSets.vue'

Because of the work before I merged I added an option to the navigation instead of using the accounts settings to configure filters. To use it with multiple accounts I implemented tabs. I'd prpose to use that and omit the sieve script editing in the accounts settings.

> I see you've started making the UI to customize filters, which is great! To summarize my to-do list, all that's needed now is:
> 
>     * a UI to add and customize filters
> 
>     * generate a Sieve script from editable filters
> 
>     * convert saved Sieve script back to editable filters
That's what I'm currently working on. My current todo:
* rework the parsing (right now I'm not happy and it's not really working)
* add more tests options
* add actions (UI and options)

**Comment by mmittelb** [comment]
Hey good to hear from you.

> Took a look at your changes. It looks like you're mistaken the account settings for the global mail settings. I've already added a "Filters" section and Sieve account settings to accounts for them to be configured. Check the example below to find the account settings:

I saw that section and configured the sieve parameters. But when I tried to load scripts with your getScripts function in 'src/service/FiltersService.js' I ran into that error. If you want to reproduce you can change the const scripts variable in the fetchSieveScripts action (src/store/actions.js) and uncomment the created() part in 'src/components/SieveFilterSets.vue'

Because of the work before I merged I added an option to the navigation instead of using the accounts settings to configure filters. To use it with multiple accounts I implemented tabs. I'd prpose to use that and omit the sieve script editing in the accounts settings.

> I see you've started making the UI to customize filters, which is great! To summarize my to-do list, all that's needed now is:
> 
>     * a UI to add and customize filters
> 
>     * generate a Sieve script from editable filters
> 
>     * convert saved Sieve script back to editable filters
That's what I'm currently working on. My current todo:
* rework the parsing (right now I'm not happy and it's not really working)
* add more tests options
* add actions (UI and options)

**Comment by pierlon** [comment]
> But when I tried to load scripts with your getScripts function in 'src/service/FiltersService.js' I ran into that error.

I suppose you mean this error: `Horde\ManageSieve\Exception\NotAuthenticated`, which more than likely means the Sieve account settings were not saved correctly. Was the [migration](https://github.com/pierlon/mail/blob/feature/sieve-filters/lib/Migration/Version0151Date20190622040212.php) for adding the fields for Sieve settings run?

> Because of the work before I merged I added an option to the navigation instead of using the accounts settings to configure filters. To use it with multiple accounts I implemented tabs. I'd prpose to use that and omit the sieve script editing in the accounts settings.

I think it would be better to have it under each account's setting, but that's not for me to decide. I'd suggest you ask that in the original [issue on Sieve integration](https://github.com/nextcloud/mail/issues/44).

**Comment by mmittelb** [comment]
Hey Pierlon,
You were right. I messed up the database with my own backend tries and forgot to properly clean up. Sorry for that.
The parsing and generating of scripts now work with my latest push. So far I didn't implement many options but there is more to come. 
If I understand correctly your create api function only allows to upload a script with a fixed name (nextcloud.custom). Would you extend this function to upload scripts with editable names?

**Comment by pierlon** [comment]
I don't see that being a needed feature, I doubt anyone will be needing to change the name of the script. Other mail clients such as Rainloop also use a fixed name, by the way.

**Comment by mmittelb** [comment]
Quote from the issue thread: https://github.com/nextcloud/mail/issues/44#issuecomment-527927565
>So my idea would be that the GUI will present filter sets in a similar in what Roundcube does. But:
>
>    the filter sets GUI would support drag and drop sorting
>    one "main" filter set would be hidden, its purpose would be to handle other filter sets activation and sorting using Sieve's include
>
>That way Rainloop (and other) rules can still be used along side Nextcloud's rules.

I'm implementing this, that's why I need multiple scripts aka filtersets. If I wouldn't let the user name their filtersets, I would either need a database to map generated script names to the name shown in the gui or there would only be generic names, which is unconvenient for the user. I think being able to name the script is the best approach. Are you willing to implement that?

**Comment by pierlon** [comment]
Didn't know about that. As long as it can work with a clean ManageSieve installation I'm on board.

**Comment by mmittelb** [comment]
Ok great. The idea is to have one (in the gui hidden) script that is managing the includes. I have implemented a kind of 'fallback' if this script doesn't exist or isn't active.
I'm basecally done with the base functions now. The only thing not working is the saving to the managesieve server. I need an api function for deleting and uploading named scripts to finish. Meanwhile I will add a bigger variaty of sieve language options...

**Comment by mmittelb** [comment]
How is it going for you?
I would need another feature. Right now I have no way to check if the filter option is enabled. If I enable it, put the data in the form, save and then disable and save again all the data is still present in the account object. Maybe you could add a sieve enabled field to the database? Another idea would be to delete all the sieve information in the database if in the web form filters are disabled,

**Comment by mmittelb** [comment]
is it ok if I just merge and push into this branch from now on?

**Comment by pierlon** [comment]
Yea sure, that way you can keep the PR over [nextcloud/mail](https://github.com/nextcloud/mail/pull/1822) updated on my behalf.

**Comment by pierlon** [comment]
I've updated the branch to match Nextcloud's master, as well as add a param to send a custom script name.

**Comment by vogll** [comment]
Hi,
I install sieve-filters, but I see no communication with mailserver. (tested with tcpdump no packet comes)  Roundcube working, I test tls an plain auth. Can you help me ? 

My config :

`  'sieveHost' => '10.15.1.122',
    'sievePort' => '4190',
    'sieveSslMode' => 'tls',
    'sieveUser' => '%USERID%@test.domain.com',
`

**Pull request merged**
